package tests

import (
	"fmt"
	"net"
	"os"
	"strings"
	"testing"
	"time"
)

// The test infrastructure is a PER-RUN stack (scripts/test-infra/up.sh, docker-compose.test-infra.yml): random loopback host ports and generated credentials,
// no fixed port and no literal credential (T129; WF12 F1). up.sh writes them to a mode 0600 env file, .audit/test-infra/catalogizer-test-<id>/env, and prints
// its op_id and ports. Point this package at that file with CATALOGIZER_TEST_INFRA_ENV; an explicit FTP_TEST_SERVER / SMB_TEST_SERVER / WEBDAV_TEST_SERVER /
// NFS_TEST_SERVER and *_TEST_USER / *_TEST_PASS still override a single value. With neither, every Require* skips and says how to start the stack.
// The user-space NFS server publishes no host port (its clients run on the project network), so NFS is reachable here only through an explicit NFS_TEST_SERVER.
const (
	// EnvFileVariable names the variable that holds the path of the per-run env file written by scripts/test-infra/up.sh.
	EnvFileVariable = "CATALOGIZER_TEST_INFRA_ENV"

	// startHint is appended to every skip message.
	startHint = "start the stack with: scripts/test-infra/up.sh --build-id <id>  and set " + EnvFileVariable + " to the env file it names (.audit/test-infra/catalogizer-test-<id>/env)"

	// connectionTimeout is the maximum time to wait when probing a service.
	// Kept short (1 second) so tests skip quickly when infrastructure is absent.
	connectionTimeout = 1 * time.Second
)

// InfraStatus holds the reachability state of all test infrastructure services.
type InfraStatus struct {
	FTP    bool
	SMB    bool
	WebDAV bool
	NFS    bool
}

// TestInfraCredentials provides the credentials of the per-run test infrastructure services (generated by scripts/test-infra/gen_env.sh).
type TestInfraCredentials struct {
	Username string
	Password string
}

// FTPCredentials returns the FTP test credentials of the per-run stack (empty when no stack is configured).
func FTPCredentials() TestInfraCredentials {
	return TestInfraCredentials{
		Username: envOrRunEnv("FTP_TEST_USER", "TI_FTP_USER"),
		Password: envOrRunEnv("FTP_TEST_PASS", "TI_FTP_PASSWORD"),
	}
}

// SMBCredentials returns the SMB test credentials of the per-run stack (empty when no stack is configured).
func SMBCredentials() TestInfraCredentials {
	return TestInfraCredentials{
		Username: envOrRunEnv("SMB_TEST_USER", "TI_SMB_USER"),
		Password: envOrRunEnv("SMB_TEST_PASS", "TI_SMB_PASSWORD"),
	}
}

// WebDAVCredentials returns the WebDAV test credentials of the per-run stack (empty when no stack is configured).
func WebDAVCredentials() TestInfraCredentials {
	return TestInfraCredentials{
		Username: envOrRunEnv("WEBDAV_TEST_USER", "TI_WEBDAV_USER"),
		Password: envOrRunEnv("WEBDAV_TEST_PASS", "TI_WEBDAV_PASSWORD"),
	}
}

// SMBShareName returns the SMB test share name (docker-compose.test-infra.yml declares the share `testshare`).
func SMBShareName() string {
	if v := os.Getenv("SMB_TEST_SHARE"); v != "" {
		return v
	}
	return "testshare"
}

// ---------------------------------------------------------------------------
// Require* functions — call these at the start of integration tests.
// They skip the test with t.Skip() if the corresponding service is not
// reachable, rather than failing. This allows the full test suite to run
// even when test infrastructure is partially or fully absent.
// ---------------------------------------------------------------------------

// RequireFTP skips the test if the FTP test server is not reachable.
// Returns the FTP server address for use in test configuration.
func RequireFTP(t *testing.T) string {
	t.Helper()
	addr := ftpAddr()
	if !isReachable(addr) {
		t.Skipf("FTP test server not reachable at %s — "+startHint, addr)
	}
	return addr
}

// RequireSMB skips the test if the SMB test server is not reachable.
// Returns the SMB server address for use in test configuration.
func RequireSMB(t *testing.T) string {
	t.Helper()
	addr := smbAddr()
	if !isReachable(addr) {
		t.Skipf("SMB test server not reachable at %s — "+startHint, addr)
	}
	return addr
}

// RequireWebDAV skips the test if the WebDAV test server is not reachable.
// Returns the WebDAV server address for use in test configuration.
func RequireWebDAV(t *testing.T) string {
	t.Helper()
	addr := webdavAddr()
	if !isReachable(addr) {
		t.Skipf("WebDAV test server not reachable at %s — "+startHint, addr)
	}
	return addr
}

// RequireNFS skips the test if the NFS test server is not reachable.
// Returns the NFS server address for use in test configuration.
func RequireNFS(t *testing.T) string {
	t.Helper()
	addr := nfsAddr()
	if !isReachable(addr) {
		t.Skipf("NFS test server not reachable at %s — "+startHint, addr)
	}
	return addr
}

// RequireAnyInfra skips the test if none of the test infrastructure services
// are reachable. Useful for tests that can work with any available protocol.
func RequireAnyInfra(t *testing.T) InfraStatus {
	t.Helper()
	status := ProbeInfra()
	if !status.FTP && !status.SMB && !status.WebDAV && !status.NFS {
		t.Skip("No test infrastructure services reachable — " + startHint)
	}
	return status
}

// RequireAllInfra skips the test if any test infrastructure service is not
// reachable. Useful for comprehensive protocol comparison tests.
func RequireAllInfra(t *testing.T) InfraStatus {
	t.Helper()
	status := ProbeInfra()
	missing := []string{}
	if !status.FTP {
		missing = append(missing, "FTP")
	}
	if !status.SMB {
		missing = append(missing, "SMB")
	}
	if !status.WebDAV {
		missing = append(missing, "WebDAV")
	}
	if !status.NFS {
		missing = append(missing, "NFS")
	}
	if len(missing) > 0 {
		t.Skipf("Test infrastructure services not reachable: %v — "+startHint, missing)
	}
	return status
}

// ProbeInfra checks which test infrastructure services are currently reachable.
// Does not call t.Skip; returns the status for the caller to decide.
func ProbeInfra() InfraStatus {
	return InfraStatus{
		FTP:    isReachable(ftpAddr()),
		SMB:    isReachable(smbAddr()),
		WebDAV: isReachable(webdavAddr()),
		NFS:    isReachable(nfsAddr()),
	}
}

// String returns a human-readable summary of the infrastructure status.
func (s InfraStatus) String() string {
	status := func(ok bool) string {
		if ok {
			return "UP"
		}
		return "DOWN"
	}
	return fmt.Sprintf("FTP=%s SMB=%s WebDAV=%s NFS=%s",
		status(s.FTP), status(s.SMB), status(s.WebDAV), status(s.NFS))
}

// AvailableCount returns how many infrastructure services are reachable.
func (s InfraStatus) AvailableCount() int {
	count := 0
	if s.FTP {
		count++
	}
	if s.SMB {
		count++
	}
	if s.WebDAV {
		count++
	}
	if s.NFS {
		count++
	}
	return count
}

// ---------------------------------------------------------------------------
// Address resolution — env var overrides for non-default setups
// ---------------------------------------------------------------------------

func ftpAddr() string {
	return addrFor("FTP_TEST_SERVER", "TI_PORT_FTP")
}

func smbAddr() string {
	return addrFor("SMB_TEST_SERVER", "TI_PORT_SMB")
}

func webdavAddr() string {
	return addrFor("WEBDAV_TEST_SERVER", "TI_PORT_WEBDAV")
}

// nfsAddr: the user-space NFS server publishes no host port; only an explicit NFS_TEST_SERVER names one.
func nfsAddr() string {
	return os.Getenv("NFS_TEST_SERVER")
}

// addrFor returns the explicit override, else 127.0.0.1:<port of the per-run env file>, else "" (not configured).
func addrFor(override, portKey string) string {
	if v := os.Getenv(override); v != "" {
		return v
	}
	if port := runEnv()[portKey]; port != "" {
		return "127.0.0.1:" + port
	}
	return ""
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// isReachable attempts a TCP connection to the given address with a short
// timeout. Returns true if the connection succeeds, false otherwise.
// This is a lightweight probe — it does not perform protocol handshakes.
func isReachable(addr string) bool {
	if addr == "" {
		return false
	}
	conn, err := net.DialTimeout("tcp", addr, connectionTimeout)
	if err != nil {
		return false
	}
	conn.Close()
	return true
}

// envOrRunEnv reads an explicit override variable, else the key of the per-run env file, else "".
func envOrRunEnv(override, key string) string {
	if v := os.Getenv(override); v != "" {
		return v
	}
	return runEnv()[key]
}

// runEnv parses the per-run env file named by CATALOGIZER_TEST_INFRA_ENV (KEY=VALUE lines written by scripts/test-infra/gen_env.sh; data, never evaluated).
// An unset variable or an unreadable file yields an empty map: the services then count as not configured.
func runEnv() map[string]string {
	out := map[string]string{}
	path := os.Getenv(EnvFileVariable)
	if path == "" {
		return out
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if k, v, ok := strings.Cut(line, "="); ok && strings.HasPrefix(k, "TI_") {
			out[k] = v
		}
	}
	return out
}
