#!/usr/bin/env python3
"""
bank-patch-default-bodies.py — closes BLUFF-FQA-API-DEFAULT-BODY-002.

Injects per-endpoint default request bodies into bank steps that
were converted from prose without body (the original prose said
"Login" without spelling out the credentials, etc).

Idempotent: skips steps that already have a body.

Per-path body templates are deliberately small and obvious; this
is a "make the bank executable" patch, not a comprehensive test
plan. Tests that need different bodies (wrong password, registration
of a new user, etc) already had explicit bodies from step 2's
converter.

Usage:
  scripts/audit/bank-patch-default-bodies.py submodules/helix_qa/banks/full-qa-api.json
"""

import json
import re
import sys

# Per-endpoint default body templates. Match by exact path equality
# OR longest-prefix match. Keys are checked in the order listed —
# more specific paths first.
DEFAULT_BODIES = [
    # exact paths
    ("/api/v1/auth/login",          {"username": "admin", "password": "admin123"}),
    ("/api/v1/auth/logout",         {}),
    ("/api/v1/auth/refresh",        {"refresh_token": "placeholder-set-by-bank-patch"}),
    ("/api/v1/auth/register",       {
        "username": "newuser_2026",
        "password": "Password!23",
        "email": "newuser@catalogizer.local",
        "first_name": "Test",
        "last_name": "User",
    }),
    ("/api/v1/auth/change-password", {
        "old_password": "admin123",
        "new_password": "NewAdmin!23",
    }),
    ("/api/v1/admin/storage/scan",  {}),
    ("/api/v1/scans",               {"path": "/"}),
    ("/api/v1/storage/roots",       {
        "name": "default-test-root",
        "protocol": "local",
        "path": "/tmp/catalogizer-test",
        "enabled": True,
    }),
    ("/api/v1/collections",         {
        "name": "Default Collection",
        "description": "Auto-generated by bank-patch-default-bodies",
    }),
    ("/api/v1/playlists",           {
        "name": "Default Playlist",
        "description": "Auto-generated",
    }),
    ("/api/v1/favorites",           {"item_id": 1, "type": "movie"}),
]


def find_default_body(path: str):
    p = path.split("?")[0].split("#")[0].rstrip("/")
    # try exact match first
    for prefix, body in DEFAULT_BODIES:
        if p == prefix:
            return dict(body) if isinstance(body, dict) else body
    # then prefix match (so /api/v1/collections/{id} inherits collections-shape)
    for prefix, body in DEFAULT_BODIES:
        if p.startswith(prefix + "/"):
            return dict(body) if isinstance(body, dict) else body
    return None


def patch_step(step: dict, case_id: str = "", step_idx: int = 0) -> bool:
    action = step.get("action", "")
    if not isinstance(action, str) or not action.startswith("http:"):
        return False
    if "body" in step:
        return False  # already has body
    parts = action.split(maxsplit=2)
    if len(parts) < 3:
        return False
    method, path = parts[1], parts[2]
    if method not in ("POST", "PUT", "PATCH"):
        return False
    body = find_default_body(path)
    if body is None:
        return False
    # Per-entry unique names so re-running the bank doesn't trip
    # CATAPI-DEFECT-005 (duplicate-name 409). When the body has a
    # "name" field that's the generic default, suffix it with the
    # case_id + step_idx to make it unique.
    if isinstance(body, dict) and "name" in body and case_id:
        body["name"] = f"{body['name']}_{case_id}_{step_idx}"
    step["body"] = body
    step.setdefault("_patched_by", []).append("bank-patch-default-bodies")
    return True


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: bank-patch-default-bodies.py <bank.json>", file=sys.stderr)
        return 2
    path = sys.argv[1]
    with open(path) as f:
        data = json.load(f)
    patched, candidates = 0, 0
    for tc in data.get("test_cases", []):
        for idx, step in enumerate(tc.get("steps", [])):
            action = step.get("action", "")
            if isinstance(action, str) and action.startswith(("http: POST", "http: PUT", "http: PATCH")):
                candidates += 1
                if patch_step(step, tc.get("id", ""), idx):
                    patched += 1
    if patched > 0:
        with open(path, "w") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write("\n")
    print(f"{path}: {patched}/{candidates} POST/PUT/PATCH steps got default bodies")
    return 0


if __name__ == "__main__":
    sys.exit(main())
