#!/usr/bin/env python3
"""WP-07 T081 hand-written appendix digests for the pin move 10b7a06 -> a71b1767 (anchors 134, 209, 211, 230, 231, 235, 240, 267 changed; 276 new).
Each edit asserts the exact text it replaces so a drifted file fails loudly. Digests are written from submodules/constitution/Constitution.md at a71b1767."""
import re, sys

P = ".specify/memory/constitution-appendix.md"
L = open(P, encoding="utf-8").read().split("\n")


def find_block(anchor_prefix):
    for i, l in enumerate(L):
        if l.startswith("#### §" + anchor_prefix + " "):
            j = i + 1
            while j < len(L) and not L[j].startswith("#### "):
                j += 1
            return i, j
    raise SystemExit("block not found " + anchor_prefix)


def line_idx(start, end, prefix):
    hits = [k for k in range(start, end) if L[k].startswith(prefix)]
    if len(hits) != 1:
        raise SystemExit("expected exactly one line starting %r in block, got %d" % (prefix, len(hits)))
    return hits[0]


def replace_block(anchor, new_lines):
    s, e = find_block(anchor)
    # keep one trailing blank line if the old block had it
    trailing = [""] if L[e - 1] == "" else []
    L[s:e] = new_lines + trailing


CANON = "Constitution.md (constitution tip a71b1767)"

# ---- 134: EXTENSION bullet
s, e = find_block("11.4.134")
k = line_idx(s, e, "  - Classification universal (§11.4.17).")
L.insert(k, "  - EXTENSION (2026-10-05): the re-run obligation (\"MUST KEEP being re-run after each remediation round, until it returns a clean GO\") is bounded PER APPROACH by §11.4.276's declared round budget; at that ceiling the item is escalated per §11.4.276(E)(3) to a recorded operator decision, never closed, never continued round-by-round indefinitely under the same approach, and never silently relaxed to \"good enough\".")
k = line_idx(s, e + 1, "- **Source:** code-review-and-quality.md:55-67")
L[k] = "- **Source:** code-review-and-quality.md:55-67 (the 2026-10-05 EXTENSION bullet: " + CANON + " lines 9110-9111; groups/ at this tip does not carry it, see the evidence note pin-upstream-findings.md)"

# ---- 209: full rewrite
replace_block("11.4.209", [
    "#### §11.4.209 — Code-review MUST run on Opus at xhigh effort as PRIMARY substrate, with a genuine-unavailability Sonnet fallback; no Fable, no escalation tier (amended 2026-10-04)",
    "- **Source:** " + CANON + " lines 10576-10596 (groups/code-review-and-quality.md:159-173 holds the pre-amendment text, see pin-upstream-findings.md)",
    "- **Rules:**",
    "  - Operator mandate 2026-10-04 (CRITICAL), AMENDING clause (A), verbatim in canon: if Opus is not available but Sonnet is, \"we MUST USE what we have! Reviews MUST BE done. Ideally with Opus model, however Sonet MUST BE used if Opus for any reason cannot be used!\"; nothing is blocked with a review not performed; \"We MUST BE maximally efficient!\". It does not change the primary substrate. Operator mandate 2026-09-26 (CRITICAL): reviews and other heavy work are done by Opus instead of Fable; it supersedes the 2026-09-15 mandate (Opus-xhigh default with Fable-xhigh escalation) and the 2026-07-15 mandate (Fable first, Opus fallback); both withdrawn, kept as lineage only.",
    "  - Every mandatory independent code-review (§11.4.125 gate before pre-build + main build, §11.4.142 universal every-change review, §11.4.194 exhaustive review, iterated to zero-finding GO per §11.4.134) MUST be dispatched on the Opus model at `xhigh` effort as PRIMARY substrate, whatever the size or complexity of the change.",
    "  - (A) PRIMARY substrate Opus-xhigh plus a genuine-unavailability SONNET FALLBACK (amended 2026-10-04), no escalation tier, no Fable, no other fallback model: Opus at `xhigh` is the PRIMARY and preferred substrate; Fable is NOT permitted in any role (default, escalation, fallback), ever; no model other than Opus or the sanctioned Sonnet fallback, and no lower tier for Opus itself, substitutes. When Opus-xhigh is genuinely unavailable (not configured, rate-limited or unreachable, established as a captured FACT per §11.4.6, never guessed) the review MUST be dispatched on Sonnet (at the highest effort the dispatch path can set) rather than blocked. The Opus-unavailability FACT and the Sonnet substitution MUST both be recorded in the review's captured evidence (§11.4.5/§11.4.69); a Sonnet review is NEVER presented as if it ran on Opus. A review is NEVER left undone solely because Opus is unavailable while Sonnet is reachable (§11.4.183). ONLY when BOTH Opus and Sonnet are genuinely unavailable (each its own captured FACT) is the review BLOCKED and deferred: record the facts, track the owed review (§11.4.197; §11.4.21 once the self-resolution audit is exhausted); the change does NOT pass the review gate unreviewed.",
    "  - (B) Independence preserved (§11.4.70/§11.4.20): the reviewing model (Opus or the sanctioned Sonnet fallback) runs as the structurally-separated reviewer, never the author; §11.4.209 sets MODEL + EFFORT only and does not weaken independence, the iterate-until-GO loop (§11.4.134), or rock-solid captured evidence (§11.4.5/§11.4.69/§11.4.107).",
    "  - (C) A review claimed done on Fable, Haiku or any model other than Opus or the sanctioned Sonnet fallback, or below `xhigh`, or on Sonnet with no recorded Opus-unavailability fact, is a §11.4 bluff at the review-substrate layer; the review's captured evidence MUST record which model + effort actually performed it; where the dispatch path cannot set/report effort (§11.4.231(F.2) harness gap) the evidence records that gap honestly and the review is never claimed `xhigh` on an unverified basis.",
    "  - (D) Values already burned in a public repository (§11.4.10): any plaintext credential value that appeared in documentation, spec, or commit history (including as a worked example) is compromised from the moment of commit; a document illustrating this or any credential-adjacent mandate MUST NOT embed a real-looking username/password pair, even as an example, without stating it is compromised-by-disclosure and MUST NOT be relied on as a secret.",
    "  - Strengthens, does not replace, §11.4.125/§11.4.142/§11.4.194/§11.4.134; pins execution substrate, now a primary-plus-sanctioned-fallback pin. Classification universal (§11.4.17).",
    "- **Gates:** CM-COVENANT-114-209-PROPAGATION, CM-CODE-REVIEW-OPUS-XHIGH (captured evidence records model=Opus + effort=xhigh, or on a path that cannot set effort that §11.4.231(F.2) gap honestly recorded, OR model=Sonnet carrying a captured Opus-unavailability FACT under the same effort-or-honest-gap rule; a review on Fable/Haiku/any other model, recorded xhigh when the path could not set it, or on Sonnet with no recorded Opus-unavailability fact FAILs; a review recorded BLOCKED with a captured fact that BOTH Opus and Sonnet were unavailable is honest and MUST NOT fire the gate, the §11.4.201(1) false-positive guard; paired §1.1 mutations: non-Opus/non-Sonnet review, xhigh claimed where unsettable, Sonnet with no recorded fact, strip literal; gate-code is a separate work item)",
    "- **No escape hatch:** beyond the sanctioned (A) Sonnet fallback (which itself requires a captured Opus-unavailability FACT): --review-any-model, --review-lower-effort-OK, --skip-opus, --non-xhigh-review, --escalate-to-fable-or-haiku, --sonnet-fallback-without-recorded-fact, --leave-review-blocked-while-sonnet-reachable",
    "- **Honest boundary:** Pins review model + effort only; independence, iterate-until-GO and evidence requirements remain as in their own anchors; where effort cannot be set/reported that gap is recorded, never claimed as xhigh.",
    "- **Project extension (Catalogizer, binding, recorded 2026-10-06 in WP-07):** this project's own mandate is STRICTER than the upstream (A) Sonnet fallback: review runs on Opus at `xhigh` ONLY; when Opus-xhigh is genuinely unavailable the review is BLOCKED and deferred (fact recorded, owed review tracked), never run on Sonnet. A project extension may tighten canon and never weaken it, so this stricter rule stands; the upstream fallback is NOT adopted here. Adopting it requires an explicit owner decision, recorded as OD-WP07-SONNET-FALLBACK (decisions/owner-request-list.md), not made by an agent.",
    "- **Composes:** §11.4.125, §11.4.134, §11.4.142, §11.4.194, §11.4.6, §11.4.10, §11.4.20, §11.4.21, §11.4.70, §11.4.183, §11.4.196, §11.4.197, §11.4.231, §11.4.201",
    "",
][:-1])

# ---- 211: full rewrite
replace_block("11.4.211", [
    "#### §11.4.211 — Merge-conflict resolution during main->feature/product/flavor merges MUST run on Opus at xhigh effort as PRIMARY substrate, with a genuine-unavailability Sonnet fallback; no Fable (amended 2026-10-04)",
    "- **Source:** " + CANON + " lines 10610-10622 (groups/project-lifecycle-and-release.md:1453-1465 holds the pre-amendment text, see pin-upstream-findings.md)",
    "- **Rules:**",
    "  - Any merge-CONFLICT resolution while integrating the canonical trunk (`main`/`master`) into a feature/product/flavor branch (§11.4.188 cadence, §11.4.195 integration, §11.4.41 merge-first, §11.4.167(D) trunk-into-stream, §11.4.167(I) approval-gated back-merge) MUST be done on the Opus model at `xhigh` effort as PRIMARY substrate. Merge-resolution analogue of §11.4.209: pins model+effort for the DECISION-MAKING (which side to keep, union both sides without loss, marker removal, semantic reconciliation). The 2026-09-26 mandate superseded the model choice of the 2026-07-16 mandate (Fable-first); its scope and `xhigh` requirement stand. Amended 2026-10-04 by the same verbatim operator mandate as §11.4.209 (use Sonnet when Opus cannot be used; nothing blocked; maximal efficiency).",
    "  - (A) PRIMARY substrate Opus-xhigh plus genuine-unavailability SONNET FALLBACK (amended 2026-10-04), no Fable: Fable is NOT permitted in any role; no lower effort for Opus itself. When Opus-xhigh is genuinely unavailable (not configured, rate-limited or unreachable, established as FACT per §11.4.6, never guessed) the resolution MUST be carried out on Sonnet (highest effort the path can set) rather than blocked; the Opus-unavailability FACT and the Sonnet substitution MUST both be recorded in the merge's captured evidence (§11.4.5/§11.4.69), never presenting a Sonnet-resolved merge as Opus-resolved. `xhigh` is REQUIRED on whichever substrate resolves the conflict where the dispatch path can set it (careless resolution drops a commit or commits a marker, §9/§11.4.41 step 3); where it cannot (§11.4.231(F.2) harness gap) the gap is recorded, never claimed as xhigh. ONLY when BOTH Opus and Sonnet are genuinely unavailable (each its own captured FACT) is the resolution BLOCKED and deferred: record the facts, do NOT complete the merge, leave the branch quiescent with no conflict marker committed (§11.4.84/§11.4.41 step 3).",
    "  - (B) Scope: operator named tracks 2-4 (feature/product/flavor); GENERALISES per §11.4.17 to EVERY controlled main->(feature|product|flavor) merge on EVERY track that hits a conflict.",
    "  - (C) Safety preserved: sets MODEL + EFFORT only; BOUNDED BY §11.4.113 (never force-push), §9/§9.2 (no commit lost, hardlinked pre-op backup before large/risky merge), §11.4.41 step 3 (ZERO conflict markers committed, ZERO file silently dropped, union of both sides preserved), §11.4.188(4) anti-bluff (post-merge smoke GREEN + conflict-marker scan empty + no-lost-commit, captured evidence §11.4.5/§11.4.69), §11.4.84 (quiescent-only), §11.4.37/§11.4.71 (fetch-first).",
    "  - (D) A merge whose conflicts were resolved on Fable or any model other than Opus or the sanctioned Sonnet fallback, or below `xhigh`, or on Sonnet with no recorded Opus-unavailability fact, is a bluff at the substrate layer; the merge's captured evidence MUST record which model + effort resolved the conflicts (and, when blocked, the FACT that both Opus and Sonnet were unavailable); an effort the path cannot set is recorded as that gap.",
    "  - Strict extension of §11.4.209 (review-side) to merge-side; the two are the review-side and merge-side halves of the same Opus-xhigh-primary-plus-Sonnet-fallback discipline; strengthens §11.4.188/§11.4.195/§11.4.41.",
    "- **Gates:** CM-COVENANT-114-211-PROPAGATION, CM-MERGE-CONFLICT-OPUS-XHIGH (a conflict-resolving merge records model=Opus + effort=xhigh or the honest §11.4.231(F.2) gap, OR model=Sonnet with a captured Opus-unavailability FACT; Fable/other model, xhigh claimed where unsettable, or Sonnet with no fact FAILs; BLOCKED with a captured fact that both were unavailable is honest and MUST NOT fire, the §11.4.201(1) guard; paired §1.1 mutations; gate-code is a separate work item)",
    "- **No escape hatch:** beyond the sanctioned (A) Sonnet fallback (which requires a captured Opus-unavailability FACT): --merge-conflict-any-model, --skip-opus-merge-resolution, --non-xhigh-merge-conflict, --resolve-conflict-lower-effort-OK, --escalate-to-fable, --sonnet-fallback-without-recorded-fact, --leave-merge-blocked-while-sonnet-reachable",
    "- **Honest boundary:** a merge recorded BLOCKED with a captured fact that both Opus and Sonnet were unavailable MUST NOT fire the gate (false-positive guard §11.4.201(1)).",
    "- **Project extension (Catalogizer, binding, recorded 2026-10-06 in WP-07):** this project's own mandate is STRICTER than the upstream (A) Sonnet fallback: conflict resolution runs on Opus at `xhigh` ONLY; when Opus-xhigh is genuinely unavailable the resolution is BLOCKED and deferred (merge not completed, branch left quiescent), never done on Sonnet. A project extension may tighten canon and never weaken it. Adopting the upstream fallback requires an explicit owner decision, recorded as OD-WP07-SONNET-FALLBACK, not made by an agent.",
    "- **Composes:** §11.4.209, §11.4.188, §11.4.195, §11.4.41, §11.4.113, §9, §9.2, §11.4.6, §11.4.167(D)(I), §11.4.84, §11.4.37, §11.4.71, §11.4.196, §11.4.183, §11.4.231, §11.4.5, §11.4.69, §11.4.201, §11.4.17",
    "",
][:-1])

# ---- 230: add clause (D) bullets; refresh title and source
s, e = find_block("11.4.230")
L[s] = "#### §11.4.230 — Parallelized-pipeline methodology (build/validate overlap, affected-stages-only re-run, parallel multi-device testing, fan-out subagents always, incremental delivery granularity with a declared QA-build cadence; clause (D) added 2026-10-04)"
k = line_idx(s, e, "- **Source:** multi-track-and-parallelism.md:189-204")
L[k] = "- **Source:** multi-track-and-parallelism.md:189-204 for clauses (A)-(C); clause (D): " + CANON + " lines 10986-11004 (groups/ at this tip does not carry clause (D), see pin-upstream-findings.md)"
k = line_idx(s, e, "  - Classification universal; consumer supplies device set + serials")
newD = [
    "  - (D) INCREMENTAL DELIVERY GRANULARITY + DECLARED QA-BUILD CADENCE (operator mandate 2026-10-04, CRITICAL; research-derived): a long-running spec/feature ships every already-proven-correct increment as it clears its own bar, never withholding delivery until the WHOLE spec is done. Operator wording in canon: work incorporated right away; deterministic machine-evidenced validation of all supported test types; intensive testing (gates, checks, fixing, polishing) keeps running in BACKGROUND while specs are built phase by phase, story by story, task by task; builds go to QA for manual testing AS SOON AS POSSIBLE and REGULARLY; background agents keep all workable items and documents in sync. Gap closed: clause (A) overlaps validation with ONE candidate's build, §11.4.235(A) makes a batch build-eligible on source-correctness, §11.4.235(D) makes that per slice; none obliges an ELIGIBLE increment to be DELIVERED, sets a cadence, says how an incomplete spec stays safe, or binds the hand-off to tracker truth. ALL of (D.1)-(D.6) hold.",
    "  - (D.1) THE DELIVERY UNIT IS THE INCREMENT, NOT THE SPEC: each vertical, independently testable slice (§11.4.148 slicing, Small + Testable) integrates into its INTEGRATION BRANCH (trunk for main-targeted work, else the feat/ / product/ / flavor/ branch of §11.4.195 it lives on) and joins the next QA deliverable cut from that branch the moment THAT increment holds its OWN source-correctness GO per §11.4.235(A)/(D). An increment on several coexisting integration branches is obligated separately per branch. A feat/ QA build is the live-manual-testing vehicle §11.4.195(B) requires BEFORE trunk-merge (precursor, never consequence); product/ and flavor/ lines get cadence builds from their own branch; (D) relaxes neither §11.4.195(B) nor (C). Withholding a build-eligible increment because other increments are unfinished, or because its/other increments' test-instrumentation or process-doc loops are open, is a violation. An increment without its own source-correctness GO is not deliverable; incremental delivery never licenses shipping unreviewed or unproven work.",
    "  - (D.2) INCOMPLETE-SPEC, SAFE DELIVERABLE: the deliverable stays correct on every user-reachable path: EITHER the increment is a complete independently valuable vertical slice, OR the unfinished surface is LATENT (unreachable by construction, behind a release toggle, or branch-by-abstraction). A toggle is PERMITTED, never mandated, and is inventory with a carrying cost: every release toggle carries a tracked §11.4.197 removal item and a consumer-declared expiry (§11.4.35); a toggle past expiry is a §11.4.261 finding; one that must outlive its expiry is extended ONLY through a §11.4.271 waiver (rostered non-producer authoriser, new unelapsed expiry, named tracked item), never by a silent expiry edit, by enabling the unproven path, or by deleting finished work. A latent path is NOT an advertised capability (§11.4.266) until enabled and proven.",
    "  - (D.3) A DECLARED QA-BUILD CADENCE, NOT A ONE-SHOT: every project declares as DATA (§11.4.35) its QA-build trigger: `per-increment`, `periodic` (fixed interval) or `whichever-first`; an undeclared project gets `per-increment` (safe default, §11.4.101). A periodic or whichever-first interval is recorded as DATA with a written justification and stated in every QA hand-off record (no numeric maximum is set; any cap is an operator decision, §11.4.66). When an integration branch holds build-eligible content not yet in a QA build cut from it and the trigger has fired, a QA deliverable MUST be cut from that branch and handed to QA for ongoing manual testing (§11.4.185). Builds COALESCE: a build in flight covers every increment that landed before it started, later increments roll into the NEXT build; a build that FAILS or is REFUSED at §11.4.236 covers NOTHING; \"completed\" means HANDED TO QA, not merely the build process exiting 0. Each deliverable is a §11.4.235(B) cycle boundary with its own monotonic version increment (§11.4.151), passes §11.4.236 readiness on its own candidate fingerprint, built once then promoted (§11.4.264). The §11.4.236 mandated validation for a cadence build is at minimum the source-correctness GO plus the §11.4.235(A) pre/post-build gates, PLUS every operator-declared blocker bound to the QA-deploy seam and any §11.4.239 critical-invariant scenarios the increment touches, NOT the open background-hardening backlog. \"Deliverable\" is project-defined DATA (binary, container, device image, or for dev-tooling/governance features the demonstrable testable state at a fingerprinted commit).",
    "  - (D.4) CONTINUOUS BACKGROUND HARDENING THAT NEVER BLOCKS THE NEXT INCREMENT: test-instrumentation hardening, gate/check/mutation authoring, polishing, and fixes for QA findings on already-delivered increments run as standing background streams (§11.4.103/§11.4.192/clause (C)), each a tracked item (§11.4.197) driven to its own zero-finding GO (§11.4.134, not relaxed), landing on its integration branch as it reaches GO and riding the NEXT cadence build. They never gate a LATER increment's build-eligibility, with two exceptions that follow from existing anchors: an open source-defect finding (§11.4.235(D)) in code the later increment touches or depends on is a source-defect of that increment too; and a huge blocker still triggers §11.4.129 STOP, fix-all, full restart.",
    "  - (D.5) NEVER-STALE TRACKING IS A PRECONDITION OF EVERY HAND-OFF: §11.4.106(F), §11.4.229, §11.4.202/§11.4.208/§11.4.210, §11.4.148 and §11.4.197 apply at EVERY increment landing and EVERY cadence build; each QA hand-off records the deliverable's fingerprint and the exact set of tracked items it contains; a hand-off whose tracker or documents disagree with the deliverable (item done whose fix is absent from that build, or a fix in the build no item records) is a §11.4 PASS-bluff at the delivery layer.",
    "  - (D.6) QA FINDINGS ON EARLY INCREMENTS ARE STILL COVERAGE ESCAPES: earlier more frequent QA builds do not make manual QA the discovery mechanism; every defect manual QA finds triggers the §11.4.238(C) coverage-escape audit and a new automated check.",
    "  - (D) honest boundary: changes WHEN and HOW OFTEN proven-correct work reaches QA, NOT what gates a release candidate; does not weaken §11.4.129, §11.4.40 (a cadence QA build is not a tag), §11.4.185, §11.4.236, §11.4.264/§11.4.265, §11.4.134 or §11.4.235(D)'s conservative default (an unclassifiable finding is a source-defect). Research grounding stated honestly in canon (DORA small batches, Hodgson toggle taxonomy, branch-by-abstraction, SAFe cadence, GitHub Next Continuous AI as direction only); no published methodology combining per-increment QA delivery with continuous agent hardening streams was found, the composition is the clause's own synthesis. §11.4.230's next free clause letter is (E); never reuse (A)-(D).",
    "  - (D) recommended gates: CM-INCREMENT-DELIVERED-NOT-SPEC-WITHHELD (FAIL: an increment holding its source-correctness GO is absent from every handed-to-QA or in-flight QA build from its integration branch after the trigger fired and no build from that branch is in flight, with coalescing so waiting on an in-flight build's successor is never a FAIL and a failed/refused build counts as neither completed nor in flight; FAIL, the §11.4.201(1) dual guard: an increment WITHOUT that GO appears in a QA build), CM-QA-BUILD-CADENCE-DECLARED (FAIL: build-eligible content uncovered after the trigger fired with no build in flight; a periodic/whichever-first interval with no justification; an absent declaration must resolve to per-increment, never to no cadence), CM-RELEASE-TOGGLE-TRACKED-EXPIRY (FAIL: a toggle with no tracked removal item or no expiry, or past expiry), CM-QA-HANDOFF-TRACKER-IN-SYNC (FAIL: a hand-off item set disagrees with the deliverable's contents); paired §1.1 mutations; gate-code is a separate work item, NOT claimed shipped.",
]
L[k:k] = newD
k = line_idx(s, e + len(newD), "- **No escape hatch:** --sequential-build-then-validate")
L[k] = L[k] + " (clause (D) adds no new flag; the canon's no-escape-hatch list is unchanged)"

# ---- 231: (E), (F.3) wording; Classification line mention
s, e = find_block("11.4.231")
k = line_idx(s, e, "  - (E) HARD PINS OVERRIDE THE DEFAULT for their scopes")
L[k] = ("  - (E) HARD PINS OVERRIDE THE DEFAULT for their scopes: §11.4.209 (every mandatory independent code-review, §11.4.125/.142/.194 iterated to GO per §11.4.134, runs on Opus at `xhigh` effort as PRIMARY substrate, with a genuine-unavailability Sonnet fallback amended 2026-10-04; no Fable, no Haiku, no other model; BLOCKED only when BOTH Opus and Sonnet are genuinely unavailable, never a lower tier or any other model) and §11.4.211 (every main->feature/product/flavor merge-CONFLICT resolution on the SAME Opus-xhigh-primary-plus-Sonnet-fallback substrate, blocked only when both are genuinely unavailable). Review and conflict resolution are NOT eligible for sonnet/opus-by-complexity dispatch; dispatching them elsewhere than the §11.4.209/§11.4.211 Opus-xhigh-primary-plus-sanctioned-Sonnet-fallback substrate violates THOSE anchors. (This project's own extension keeps these two scopes Opus-xhigh-only, see the §11.4.209 project-extension line.)")
k = line_idx(s, e, "  - (F.3) Hard-pin floor")
L[k] = ("  - (F.3) Hard-pin floor: §11.4.209 reviews and §11.4.211 merge-conflict resolutions run at `xhigh` on Opus as PRIMARY substrate (or, on a captured genuine Opus-unavailability FACT, on the sanctioned Sonnet fallback of §11.4.209/§11.4.211, amended 2026-10-04; Fable and Haiku remain forbidden in every role); the general effort ladder NEVER tiers those scopes below `xhigh` where the dispatch path can set it; a review/merge-conflict resolution run below `xhigh` on a path that COULD set it, or on a model other than Opus or the sanctioned Sonnet fallback, is a §11.4.209/§11.4.211 violation, not a valid application of this ladder.")

# ---- 235: clause (D)
s, e = find_block("11.4.235")
k = line_idx(s, e, "- **Source:** project-lifecycle-and-release.md:1509-1521")
L[k] = "- **Source:** project-lifecycle-and-release.md:1509-1521 for clauses (A)-(C); clause (D): " + CANON + " lines 11113-11117 (groups/ at this tip does not carry clause (D), see pin-upstream-findings.md)"
k = line_idx(s, e, "  - (C) STANDING DEFAULT")
L.insert(k + 1, "  - (D) FINDING-LAYER CLASSIFIER (added 2026-10-03, research-derived from the §11.4.230 four-agent audit of a consuming project's SpecKit-004 T048 remediation saga): the decidable split clause (A) relies on, mandatory at every §11.4.125/§11.4.142/§11.4.194 review verdict. Every finding a verdict records (§11.4.115(F) machine-written) MUST carry exactly one `finding_layer` from the closed set {source-defect | test-instrumentation | process-doc}, a field DISTINCT from any other per-finding classification the record carries (e.g. a pre-existing `class` field {mechanical | judgment | false-positive} is a different axis). `source-defect`: the finding shows the SHIPPED artifact's own behaviour wrong, unsafe or exploitable as it will run, OR invalidates the evidence that proves THIS batch's fixes correct (their §11.4.115 RED->GREEN guard, §11.4.108 runtime signature, or covering test per §11.4.125(6); a proving guard that cannot fail, or whose reviewer-authored mutation survives per §11.4.194(6)(d), means the source is NOT proven-correct). `test-instrumentation`: concerns only future-regression coverage, mutation-guard robustness or detection completeness of a guard/gate/meta-test whose protected behaviour was ALREADY proven, with no production decision path shown wrong and no proof-of-this-batch evidence invalidated. `process-doc`: labels, comments, citations or prose with no behavioural effect. The layer is recorded by the REVIEWER (§11.4.240/§11.4.249); the producer MAY contest it only via a fresh review round and MUST NOT lower it unilaterally. A finding that cannot be decidably classified defaults to `source-defect` (conservative-safe, §11.4.201(4), §11.4.101). §11.4.134 is NOT relaxed: every finding of every layer is still driven to zero-finding zero-warning GO in its own loop; (D) decides only which GO is the BUILD GO-signal: a batch/slice is BUILD-ELIGIBLE when its source-defect findings reach that GO, while outstanding test-instrumentation/process-doc findings continue as their own tracked §11.4.197 item on a §11.4.230(A)/§11.4.103 parallel stream. A BATCHED review spanning many slices/files MUST record its verdict PER SLICE/FILE, never one undifferentiated verdict. Applies prospectively; recorded verdicts are never rewritten or reclassified (§11.4.6/§11.4.268). Honest boundary: classification is a required, recorded, reviewer-owned decision, not made easy or infallible.")
k = line_idx(s, e + 1, "- **Gates:** CM-COVENANT-114-235-PROPAGATION")
L[k] = L[k].rstrip() + ", CM-REVIEW-FINDING-CLASS-RECORDED (clause (D): FAIL a batched-review verdict covering more than one slice/file with no per-slice verdict or no per-finding `finding_layer`; FAIL a slice marked build-eligible while any source-defect finding in it has not reached GO; FAIL a `finding_layer` lowered by the producer without a fresh review round; paired §1.1 mutation; gate-code is a separate work item, NOT claimed shipped, registered as a tracked deferral in scripts/gates/gate_ledger_deferrals.tsv; it binds additively by computing whether the existing `source_review_go` marker may be written). Upstream correction: CM-BUILD-ON-SOURCE-PROVEN-NOT-TEST-SIDE and CM-VERSION-INCREMENT-ON-DEPLOY ARE implemented (scripts/gates/cm_build_on_source_proven_not_test_side.sh, cm_version_increment_on_deploy.sh and their paired mutation tests); the earlier 'gate-code = separate work item' disclaimer for those two was stale."
k = line_idx(s, e + 1, "- **Honest boundary:** relocates the test-instrumentation")
L[k] = L[k].rstrip() + " Clause (D) supplies the mandatory classification mechanism this boundary's own test presupposes: a review that never classifies its findings has not applied this boundary, it has merely stated it."

# ---- 240 (F)(2) sentence
s, e = find_block("11.4.240")
k = line_idx(s, e, "  - (F) Independence-tier vocabulary")
old = "or §11.4.209 (code review on Opus at xhigh), which remain in force"
assert old in L[k]
L[k] = L[k].replace(old, "or §11.4.209 (code review on Opus at xhigh as PRIMARY substrate, with a genuine-unavailability Sonnet fallback, amended 2026-10-04; Fable and Haiku remain forbidden in every role), which remain in force")

# ---- 267 EXTENSION
s, e = find_block("11.4.267")
k = line_idx(s, e, "  - (E) N is consumer-supplied DATA")
L.insert(k + 1, "  - (E) EXTENSION (2026-10-05): where the operator mandates a ceiling on N for a specific, named loop, that ceiling is recorded with its own verbatim mandate in its own anchor (§11.4.276 for the independent-review loop); this is the only form of N-bound literal this clause permits; the consumer's declared N within that ceiling remains consumer DATA, never the literal ceiling itself.")

# ---- 276 new block, after the 275 block
s, e = find_block("11.4.275")
blk = [
    "#### §11.4.276 — Review-round budget: every independently-reviewed work item converges within a declared budget of at most 7 rounds (5-7, consumer-declared), by front-loading ground truth, class-exhaustive enumeration, real-path tests and a declared threat boundary, with a binding methodology change at round 3 (User mandate, 2026-10-05)",
    "- **Source:** " + CANON + " lines 11928-11966 (this anchor is in no groups/*.md file at this tip, see pin-upstream-findings.md)",
    "- **Rules:**",
    "  - Verbatim operator mandate (2026-10-05, CRITICAL): \"Make sure we never ever get to such extremely high never ending review rounds count! Determine exact causes of issues we are facing with deep planning and exhaustive analisys so all work ALWAYS gets done with 5 to 7 reviews max! This MUST BE mandatory part of the constitution!!! Reasonable reviews rounds count with fully deterministically validated and verified working results produced!\"",
    "  - Forensic FACTS (genericised): one reference consuming project ran four independently-reviewed work items to 7, 10+, 30 and 39+ rounds in one week; the recorded findings show five avoidable mechanisms: (1) wrong-model ground truth (a build-configuration fix and its verifying gate both built on a simplified model of an external build tool's inheritance mechanism, the gate running the real tool on a hand-simplified fixture and so reporting GREEN on a fix that could never work); (2) instance-at-a-time closure of a known class (a command-shadowing gate hardened one command name per round across consecutive rounds; a 'close the whole class' instruction met by fixing a syntactic proxy token, the same defect family returning in four consecutive rounds); (3) fixer-authored tests that never drive the real code (re-implemented or text-extracted logic, so the reviewer's mutations of the real code survived); (4) non-binding escalation signals (the heuristic-tower anchor §11.4.250 invoked about thirty times, the stall anchor §11.4.267 having no declared retry bound, a reviewer-recommended structural fix deferred in two successive rounds while in-file point hardening continued); (5) scope drift (an out-of-scope tangent absorbed by a review loop while the round counter kept accruing against the original item). Genuinely new findings legitimately needing another round also occurred; iteration as such is not the defect, rounds spent re-discovering what one front-loaded investigation would have found are.",
    "  - Boundary stated first (§11.4.227): §11.4.134 governs the GO bar and the obligation to re-run until met; §11.4.267 the attempt record and an undeclared stall bound N; §11.4.250 the heuristic-tower signal; none bounds the review loop's LENGTH or binds a concrete action to a round NUMBER. §11.4.276 adds exactly that: (A) the ceiling, (E) the round-3 checkpoint and the ceiling escalation. (B)-(D) add no new substantive duty, they fix WHEN existing duties are discharged ((B) binds §11.4.6/§11.4.99/§11.4.102 phase 1/§11.4.199/§11.4.226 to a recorded artifact before the first fix; (C) binds §11.4.250/§11.4.201(7)(b) to the round that first meets a nameable class; (D) binds §11.4.224(A)/§11.4.194(6)(d)/§11.4.115(F)/§11.4.235(D) to every remediation round's regression set).",
    "  - (A) DECLARED ROUND BUDGET, HARD CEILING 7: every work item through the §11.4.125/§11.4.134/§11.4.142/§11.4.194 review loop carries a round budget R_max declared by the consumer as DATA (§11.4.35) in the closed range 5 <= R_max <= 7; an absent declaration resolves to 5 (conservative, escalation fires earliest, §11.4.101). The ceiling is a constitutional literal because the operator supplied it verbatim (same pattern as §11.4.246); the consumer's R_max within it IS its §11.4.267 N for the review loop and remains consumer DATA. A round = one independent review verdict on the item (uncommitted or already-pushed work), counted from the first review and recorded with the item's review record; a review that never received its brief, or crashed without a verdict, is recorded but not counted. Splitting, renaming or re-filing the item does NOT reset the count unless (E)(3) applies. A tracked item created from a finding raised during a budgeted item's review inherits its consumed round count, except a finding outside a scope/threat boundary declared before round 1 under (E)(2), which starts a fresh budget; recurrence identity follows §11.4.214 (link, never mint).",
    "  - (B) GROUND TRUTH BEFORE THE FIRST FIX: for any change or finding whose correctness depends on a system the author does not own (build tool, compiler, interpreter or shell semantics, kernel, runtime, third-party library, protocol) the author MUST, before the first fix attempt, record a ground-truth probe: (1) the authoritative source of the behaviour (the tool's own source or normative specification, cited by file and line, not a summary or memory); (2) a minimal fixture executed on the REAL tool through its REAL composition path (the actual inheritance, sourcing, linking or dispatch mechanism the product uses; a hand-simplified approximation does not count); (3) the recorded behavioural model the fix relies on. The fix's own verifying gate or test MUST exercise the same real path; a gate verified on a simplified model is wrong-layer evidence (§11.4.226) and cannot support a GO.",
    "  - (C) CLASS-EXHAUSTIVE ENUMERATION ON FIRST INSTANCE: when a finding is an instance of a class (bypass via name resolution, unguarded external command, masked character, mutation-surviving test, missed parse case) the round that fixes it MUST (1) name the class; (2) enumerate every member across the item's whole scope with a mechanical instrument whose null result is control-needle-proven (§11.4.201(7)(b)) and record that inventory; (3) close every member or scope one out explicitly with a reason and a tracked item (§11.4.197). Fixing only the reported instance when the class is nameable is a §11.4.276(C) violation. If the enumeration needs a tool that does not exist (e.g. a decision-path vs display-only call classifier), building it IS the remediation work; 'no classifier yet' is not a reason to fall back to instance-by-instance fixes. A claim a class is closed MUST cite the inventory artifact; a fix that closes a syntactic proxy instead of the class is an unclosed finding (§11.4.250).",
    "  - (D) REAL-PATH TESTS AND REVIEWER MUTATIONS ADOPTED VERBATIM: every regression test added in a remediation round MUST drive the real shipped artifact through its real invocation path (§11.4.224(A)); a test re-implementing the guarded logic inline, or running extracted source text outside the artifact's own process, guards nothing and is a source-defect finding under §11.4.235(D). Every mutation a reviewer reported as surviving is added to the item's mutation set verbatim and must FAIL the suite before the next review is requested (§11.4.194(6)(d), §11.4.115(F)). The fixer runs the item's full regression set and the reviewer's previous attacks against the fix before requesting review; the dispatch seam REFUSES to start a review when that record is absent (never counted, never dispatched). A review that WAS dispatched and returned a verdict always counts as a round, even if its triggering record was later found deficient.",
    "  - (E) BINDING METHODOLOGY CHANGE AT ROUND 3 AND THE CEILING ESCALATION: (1) at round 3 and every later round the round's fixer MUST first record a convergence assessment classifying every finding so far as new-class / same-class-as-earlier / regression-introduced-by-a-fix / wrong-layer-evidence. If two or more findings share a defect class named under (C) (not merely a shared §11.4.235(D) finding layer) with at least one non-MINOR finding in that class, any finding reappeared after being reported fixed, or any finding was wrong-layer evidence, the next round MUST be a structural round: a fresh fixer instance that did not author rounds 1-2 (the reviewer remains structurally separate throughout, §11.4.240), re-deriving (B) from first principles, re-running the (C) enumeration over the whole scope, and replacing the approach rather than adding a layer (§11.4.250). A structural fix a reviewer recommended may not be deferred past this point without a recorded operator decision (§11.4.66). (2) Every review declares, before round 1, its scope and acceptance boundary (and for adversarial/security reviews the threat model: which actor capabilities are in scope and the seam at which the defence lives) so a zero-finding GO under §11.4.134 is reachable; findings outside it are tracked items, not loop-extending findings; the boundary is fixed at round 1 and changes only by recorded operator decision, narrowing it mid-loop to reach GO is a §11.4.6 fabrication. (3) If round R_max returns anything but GO the item MUST NOT run round R_max+1 under the same approach: it stops and goes to a recorded operator decision (§11.4.66) carrying the finding classification, the evidence of which of (B)-(D) was skipped or failed, and the options (re-scope into smaller slices per §11.4.148; replace the approach with the structural design as a new item; or accept residual LOW findings only through a §11.4.271 waiver). Only a recorded operator decision opens a new budget. The escalated item is parked per §11.4.101/§11.4.267(F), parking only that work unit while the autonomous loop (§11.4.126) continues all other work and the pending decision is surfaced in every §11.4.97 progress report. Every breach is also recorded as a process escape and audited for which of (B)-(D) would have prevented it (§11.4.238(C) pattern).",
    "  - (F) NOTHING HERE LOWERS THE BAR: the budget bounds the NUMBER of rounds, never what a round must establish; §11.4.134's zero-finding zero-warning GO bar is unchanged and its re-run obligation is bounded per approach by R_max, after which (E)(3) governs; §11.4.209's substrate, §11.4.235(D)'s finding layers and §11.4.262's machine evidence are unchanged. Reaching R_max without GO never produces a GO, a 'good enough' or a silent close: the item stays open until a recorded operator decision.",
    "  - Classification: universal (§11.4.17); the consumer supplies R_max (5-7), its review-record location, and its probe and inventory artifact paths as DATA (§11.4.35).",
    "- **Gates:** CM-COVENANT-114-276-PROPAGATION (literal 11.4.276 as a block-start, exactly once per governance file, lockstep content-hash equality per §11.4.227(B); implemented upstream in scripts/gates/cm_covenant_114_276_propagation.sh with its paired mutation test), CM-REVIEW-ROUND-BUDGET (every reviewed item has a declared R_max in 5-7 or the default 5 and a round count from its review record; a round R_max+1 dispatched with no recorded operator decision FAILs; an item closed without GO FAILs), CM-REVIEW-ROUND3-CONVERGENCE-ASSESSMENT (every round >= 3 carries a convergence classification; a non-structural round after an assessment that triggered (E)(1) FAILs; an adversarial review with no pre-round-1 threat boundary FAILs), CM-FIX-GROUND-TRUTH-AND-CLASS-INVENTORY (a fix touching a declared external-system surface with no ground-truth probe record, or a class finding fixed with no inventory artifact, FAILs); the three mechanism gates are registered upstream as tracked deferrals OWED-GATE-111..113 (gate-code is a separate work item, NOT claimed shipped); paired §1.1 mutations (dispatch round 8 with no decision record; delete the round-3 classification or follow a same-class trigger with a point-fix round; strip the probe record or mark a class closed with no inventory; strip the literal); golden-FALSE per §11.4.201(1): an item reaching GO at round 4 with a round-3 assessment showing only new-class findings, a recorded probe and an inventory for its one class finding fires no gate",
    "- **No escape hatch:** --unbounded-review-rounds, --fix-instance-not-class, --defer-ground-truth-probe, --narrow-threat-model-to-reach-go, --reset-round-count-on-refile, --defer-structural-fix-past-round-3",
    "- **Honest boundary:** the anchor does not promise every item converges within R_max rounds; some problems are hard and a determined adversarial reviewer can keep finding real defects in an in-process defence whose threat boundary is wider than its design. It removes the avoidable round inflation (wrong external-system model, one member of a known class, tests that never drove the real code, an un-actioned stall signal, an unrelated tangent accruing against the wrong item); when a problem is genuinely hard (E)(3) turns an open-ended loop into a bounded evidence-backed operator decision. The cap counts rounds, not effort, and licenses no shallower review. The operator's wording ('5 to 7 reviews max') is read as a ceiling with a mandatory escalation at that ceiling, not a guarantee every item closes within it; that reading was recorded in canon and surfaced to the operator at landing per §11.4.66.",
    "- **Composes:** §11.4.6, §11.4.66, §11.4.101, §11.4.102, §11.4.125, §11.4.134, §11.4.142, §11.4.148, §11.4.194(6)(d), §11.4.197, §11.4.201(7)(b), §11.4.209, §11.4.214, §11.4.224(A), §11.4.226, §11.4.235(D), §11.4.238(C), §11.4.240, §11.4.250, §11.4.267, §11.4.271, §1.1",
    "",
]
L[e:e] = blk

open(P, "w", encoding="utf-8").write("\n".join(L))
print("appendix hand edits applied; lines now", len(L))
