#!/usr/bin/env bash
# gen_engine_options.sh - regenerates scripts/containers/tests/engine_options.tsv, the ground truth for the option tables of
# scripts/containers/check_pins.sh (which options of `<engine> run|create|pull` and of the engine itself take a separate value).
# podman rows are PARSED from the live `podman <verb> --help` text (run + create -> table `run`, pull -> table `pull`, `podman --help` ->
# `global`); an option whose help line carries a type word takes a separate value, one without is boolean (an optional-value `[=..]`
# form is boolean here: only `--opt=value` carries its value). docker rows are the options table of the docker CLI reference
# (docs.docker.com container_run.md, read 2026-10-07; docker is not installed on this host: UNCONFIRMED against a live docker).
# nerdctl and buildah are not installed: their options are UNCONFIRMED and treated like docker's / podman's (see docs/scripts/check_pins.md).
# Usage: gen_engine_options.sh [OUTFILE]   (default: engine_options.tsv beside this script). Needs podman on PATH.
set -eu
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-$HERE/engine_options.tsv}"
command -v podman >/dev/null 2>&1 || { echo "gen_engine_options: podman is required" >&2; exit 2; }
exec python3 -I - "$OUT" <<'PY'
import re, subprocess, sys
out = sys.argv[1]
def help_text(args):
    return subprocess.run(["podman"] + args + ["--help"], capture_output=True, text=True, check=True).stdout
def parse(text):
    res, insec = {}, False
    for ln in text.split("\n"):
        if re.match(r"^[A-Z][A-Za-z ]*:$", ln):
            insec = ln.strip() == "Options:"
            continue
        if not insec:
            continue
        m = re.match(r"^\s+(?:(-[A-Za-z0-9]),\s+)?(--[A-Za-z0-9-]+)(?: (\S+))?(?:\s{2,}\S|\s*$)", ln)
        if not m:
            continue
        kind = "value" if m.group(3) and "[=" not in m.group(3) else "bool"
        for n in (m.group(1), m.group(2)):
            if n:
                res[n] = kind
    return res
ver = subprocess.run(["podman", "--version"], capture_output=True, text=True, check=True).stdout.strip()
rows = {}   # (table, option) -> (kind, source)
def put(table, opts, src):
    for o, k in opts.items():
        prev = rows.get((table, o))
        if prev and prev[0] != k:
            k = "value"          # a conflict across verbs of one table: a value option wins (the operand search must not take its value as the image)
        rows[(table, o)] = (k, src if not prev else prev[1] + "+" + src)
src = ver.replace(" ", "-")
put("run", parse(help_text(["run"])), src + ":run")
put("run", parse(help_text(["create"])), src + ":create")
put("pull", parse(help_text(["pull"])), src + ":pull")
put("global", parse(help_text([])), src + ":global")
D = "docker-docs-container_run.md-2026-10-07"
dv = """--add-host --annotation -a --attach --blkio-weight --blkio-weight-device --cap-add --cap-drop --cgroup-parent --cgroupns --cidfile --cpu-count
--cpu-percent --cpu-period --cpu-quota --cpu-rt-period --cpu-rt-runtime -c --cpu-shares --cpus --cpuset-cpus --cpuset-mems --detach-keys --device
--device-cgroup-rule --device-read-bps --device-read-iops --device-write-bps --device-write-iops --dns --dns-option --dns-search --domainname
--entrypoint -e --env --env-file --expose --gpus --group-add --health-cmd --health-interval --health-retries --health-start-interval
--health-start-period --health-timeout -h --hostname --io-maxbandwidth --io-maxiops --ip --ip6 --ipc --isolation -l --label --label-file --link
--link-local-ip --log-driver --log-opt --mac-address -m --memory --memory-reservation --memory-swap --memory-swappiness --mount --name --network
--network-alias --oom-score-adj --pid --pids-limit --platform -p --publish --pull --restart --runtime --security-opt --shm-size --stop-signal
--stop-timeout --storage-opt --sysctl --tmpfs --ulimit --umask -u --user --userns --uts -v --volume --volume-driver --volumes-from -w --workdir""".split()
db = "-d --detach --init -i --interactive --no-healthcheck --oom-kill-disable --privileged -P --publish-all -q --quiet --read-only --rm --sig-proxy -t --tty --use-api-socket".split()
put("run", {o: "value" for o in dv}, D)
put("run", {o: "bool" for o in db if ("run", o) not in rows}, D)
put("pull", {"--platform": "value", "-a": "bool", "--all-tags": "bool", "--disable-content-trust": "bool", "-q": "bool", "--quiet": "bool"}, "docker-docs-image_pull")
put("global", {o: "value" for o in "--config -c --context -H --host -l --log-level --tlscacert --tlscert --tlskey".split()}, "docker-docs-cli")
put("global", {o: "bool" for o in "-D --debug --tls --tlsverify -v --version".split() if ("global", o) not in rows}, "docker-docs-cli")
with open(out, "w") as f:
    f.write("# engine_options.tsv - generated by gen_engine_options.sh (do not edit by hand); table<TAB>option<TAB>kind<TAB>source\n")
    for (t, o), (k, s) in sorted(rows.items()):
        f.write("%s\t%s\t%s\t%s\n" % (t, o, k, s))
print("gen_engine_options: %d rows -> %s" % (len(rows), out))
PY
