# T043 paired mutations of scripts/commit-push-all.sh and scripts/repo/host_entry/cpa-host (data of run_wp04i_mutations.sh).
# Each entry: id, file (relative to the source root), a list of (old, new) literal replacements (every `old` must occur, all occurrences are
# replaced), the section of scripts/repo/tests/test_commit_push_all.sh (CPA_ONLY) that must FAIL, and what the mutation models.
# A mutation is CAUGHT when the matrix section exits non-zero on the mutated copy while the unmutated copy passes it (the control).
# `equivalent` entries are mutations that the matrix cannot distinguish because a second layer enforces the same property; they are listed, never counted
# as caught, and never silently dropped (constitution 11.4.6).
CPA = 'scripts/commit-push-all.sh'
HOST = 'scripts/repo/host_entry/cpa-host'
MUTANTS = [
 ('M01_no_scope_check', CPA, [('"$RD/scope_check.sh" --root "$TARGET" --paths-from "$CPA_RUN/paths.list" >"$CPA_RUN/scope.out" 2>&1; rc=$?', ': >"$CPA_RUN/scope.out"; rc=0')], '5 scope', 'remove a stage: S2 never runs (the .env fixture is committed)'),
 ('M02_no_cheap_checks', CPA, [('"$RD/validate_cheap.sh" "${vc[@]}" >"$CPA_RUN/validate.out" 2>&1; rc=$?', ': >"$CPA_RUN/validate.out"; rc=0')], '1 exit', 'remove a stage: S3 never runs (the failing-check fixture is committed)'),
 ('M03_no_push', CPA, [('"$RD/push_recursive.sh" "${pr[@]}" >"$CPA_RUN/push.out" 2>"$CPA_RUN/push.err"; rc=$?', ': >"$CPA_RUN/push.out" 2>"$CPA_RUN/push.err"; rc=0')], '1 exit', 'drop the remote loop: S6 pushes to no remote'),
 ('M04_verify_without_remote', CPA, [('if [ -n "$LOCAL_ONLY" ]; then vf+=(--no-remote); else vf+=(--fetch); fi', 'vf+=(--no-remote)')], '8 verifier', 'S7 never contacts a remote (an unproven remote is not seen)'),
 ('M05_failing_check_is_success', CPA, [('fail S3 10 check_failed', 'log S3 ignored_failure')], '1 exit', 'treat a refusal as success: a failing S3 check does not stop the run'),
 ('M06_scope_refusal_is_success', CPA, [('13) fail S2 13 scope_refused', '13) log scope_ignored')], '5 scope', 'treat a refusal as success: an S2 refusal does not stop the run'),
 ('M07_lock_never_released', CPA, [('if [ "$LOCKED" = 1 ]; then "$LO/release.sh"', 'if [ "$LOCKED" = 9 ]; then "$LO/release.sh"')], '1 exit', 'the lock outlives the run'),
 ('M08_report_only_on_success', CPA, [('  if [ -d "$CPA_RUN" ]; then\n    files=', '  if [ -d "$CPA_RUN" ] && [ "$rc" = 0 ]; then\n    files=')], '1 exit', 'S8 writes no report on a failing exit path'),
 ('M09_verdict_already_go_removed', CPA, [('fail S5 20 verdict_already_go', 'log verdict_ignored')], '6 held', 'a hold on a verdict that already holds GO commits'),
 ('M10_held_paths_unheld', CPA, [('[ -z "$hf" ] || cr+=(--held-from "$hf")', ':')], '6 held', 'S5 ignores the held rows: the held path is committed unheld'),
 ('M11_ignored_option', CPA, [('[ $# -le 1 ] || fail S0 20 usage_error "unexpected argument after the message: $2"', ':')], '2 usage', 'an argument after the message is silently ignored'),
 ('M12_merge_by_rebase', CPA, [('"$RD/integrate_merge.sh" "${mf[@]}" >"$CPA_RUN/integrate-merge-$st.out" 2>&1; rc=$?', 'git -C "$TARGET" rebase "origin/$BR" >"$CPA_RUN/integrate-merge-$st.out" 2>&1; rc=0')], '7 merge', 'integrate a diverged repository by git rebase instead of a merge'),
 ('M13_local_only_pushes', CPA, [('stage S6 push\nif [ -z "$LOCAL_ONLY" ]; then', 'stage S6 push\nif [ -z "" ]; then')], '4 deferral', '--local-only still pushes'),
 ('M14_skip_long_not_recorded', CPA, [('[ -z "${SKIP_LONG:-}" ] || defer SKIP_LONG "$SKIP_LONG" S0', ':')], '4 deferral', 'SKIP_LONG is not recorded: the commit carries no Deferred-Gates line'),
 ('M15_sweep_absent_not_deferred', CPA, [('else defer SWEEP_ABSENT "sweep not yet in the approved manifest (tasks.md T090, T093)" S0; fi', 'else :; fi')], '1 exit', 'an absent sweep is not recorded as a deferral'),
 ('M16_no_self_test', CPA, [('[ -n "${CPA_ROOT:-}" ] && [ -n "${CPA_RUN_ID:-}" ] || selfrefuse not_via_host_entry "CPA_ROOT or CPA_RUN_ID unset"', 'CPA_ROOT="${CPA_ROOT:-$PWD}"; CPA_RUN_ID="${CPA_RUN_ID:-direct}"'),
                           ('[ "$(realpath -- "$EXPECT" 2>/dev/null)" = "$SELF" ] || selfrefuse not_via_host_entry "own path is not the released copy of this run"', ':'),
                           ('[ -r "$SNAP" ] || selfrefuse not_via_host_entry "no trust-snapshot.json beside the released copy"', ':'),
                           ('[ -n "$want" ] && [ "$want" = "$(sha256sum "$SELF" | cut -d\' \' -f1)" ] || selfrefuse not_via_host_entry "own sha256 differs from the snapshot entry"', ':'),
                           ('[ "$msha" = "$(jq -r .manifest_sha256 "$SNAP" 2>/dev/null)" ] || selfrefuse snapshot_not_trusted "manifest_sha256 of the snapshot is not the sha256 of its entries"', ':'),
                           ('[ -s "$TRUSTF" ] || selfrefuse snapshot_not_trusted "trust file unreadable or empty"', ':'),
                           ('|| selfrefuse snapshot_not_trusted "no approval of the project records this manifest"', '|| true')], '10 host', 'the copied script runs without its self-test'),
 ('M17_host_no_rehash', HOST, [('[ "$got" = "$s" ] || { rm -rf "$RUN"; refuse approved_copy_invalid hash_mismatch', 'true || { rm -rf "$RUN"; refuse approved_copy_invalid hash_mismatch')], '10 host', 'cpa-host does not re-hash the copies it makes'),
 ('M18_host_run_id_reuse', HOST, [('mkdir "$RUN" 2>/dev/null || refuse run_id_invalid run_id_in_use "$rid"', 'mkdir -p "$RUN" 2>/dev/null'), ('[ ! -e ".audit/commit-push/$rid" ] || refuse run_id_invalid run_id_in_use "$rid"', ':')], '10 host', 'a run directory is reused (mkdir -p)'),
 ('M19_host_no_adoption_check', HOST, [('if ! git rev-list --first-parent HEAD 2>/dev/null | grep -qx -- "$adopt"; then refuse project_not_trusted adoption_commit_not_first_parent "$adopt"; fi', ':')], '10 host', 'cpa-host does not check the adoption commit against the first-parent chain'),
 ('M20_selftest_ignores_revoke', CPA, [('if jq -e --arg k "$pkey" --arg m "$msha" \'.projects[$k].history|map(select(.op=="revoke")|.manifest_sha256)|index($m)!=null\' "$TRUSTF" >/dev/null 2>&1; then selfrefuse snapshot_not_trusted revoked; fi', ':')], '10 host', 'the self-test ignores revoke rows'),
 ('M21_force_with_lease_token', CPA, [('LC_ALL=C\nSELF=', 'LC_ALL=C\nPUSHFLAG="--force-with-lease"\nSELF=')], '11 static', 'a --force-with-lease token is added to the script'),
 ('M22_no_lock', CPA, [('"$LO/acquire.sh" --purpose commit_push --run-id "$RUN_ID" --pid "$$" >"$CPA_RUN/lock.out" 2>&1; lrc=$?', ': >"$CPA_RUN/lock.out"; lrc=0')], '3 lock', 'the lock is never taken: a second run proceeds beside the first'),
 ('M23_pending_ignores_head', CPA, [('awk -F\'\\t\' -v p="$dpath" -v h="$dhead" \'$1==p && $2==h {f=1} END{exit !f}\' "$PP"', 'awk -F\'\\t\' -v p="$dpath" \'$1==p {f=1} END{exit !f}\' "$PP"')], '8 verifier', 'a pending pin row that names another sha still matches the drift'),
 ('M24_verifier_14_stays_14', CPA, [('14) fail S7 11 remote_unproven', '14) fail S7 14 remote_unproven')], '8 verifier', 'an unproven remote at S7 gives the deferral code 14'),
 ('M25_missing_report_is_clean', CPA, [('|| fail S7 20 verifier_report_unreadable "verifier exit $vrc; a missing or unreadable report is never read as clean"', '|| true')], '8 verifier', 'a verifier exit 0 with no report is read as clean'),
 ('M26_no_remote_reachable_removed', CPA, [('[ "$reach" = 1 ] || fail S0 20 no_remote_reachable', ':')], '1 exit', 'every remote unreachable is not refused at S0'),
 ('M27_deferral_write_ignored', CPA, [('|| fail "${3:-$CUR}" 20 deferral_write_failed "$1"', '|| true')], '4 deferral', 'a record_deferral.sh that fails to write its row still yields a 14'),
 ('M28_helper_status_to_10', CPA, [('*) fail S5 20 commit_failed', '*) fail S5 10 commit_failed')], '4 deferral', 'a helper exit outside its documented set is mapped to 10'),
 ('M29_held_without_local_only', CPA, [('"$RD/record_deferral.sh" --run-dir "$CPA_RUN" --flag LOCAL_ONLY --reason "held on review: push owed until the verdict is GO" --awaits-review', 'true --run-dir "$CPA_RUN" --flag LOCAL_ONLY --reason "held on review: push owed until the verdict is GO" --awaits-review')], '6 held', 'a held commit carries no LOCAL_ONLY in its Deferred-Gates line'),
 ('M30_no_pending_pin_row', CPA, [("{ [ -f \"$pp\" ] && awk -F'\\t' -v p=\"$REPO\" '$1!=p' \"$pp\"; printf '%s\\t%s\\t%s\\n' \"$REPO\" \"$nh\" \"$RUN_ID\"; } > \"$tmp\"", '{ :; } > "$tmp"')], '9 repo', 'a --repo run records no pending pin row'),
 ('M31_report_without_hashes', CPA, [("jq -R -s 'split(\"\\n\")|map(select(length>0)|split(\"\\t\")|{(.[1]):.[0]})|add // {}'", "jq -R -s '{}'")], '1 exit', 'the report holds no sha256 of the run directory'),
 ('M32_hooks_not_disabled', CPA, [('export "GIT_CONFIG_KEY_$_n=core.hooksPath" "GIT_CONFIG_VALUE_$_n=$CPA_RUN/no-hooks"; export GIT_CONFIG_COUNT=$((_n+1))', ':')], '12 hooks', 'git hooks run in the commit, merge and push of a run (no-hooks directory unused)'),
 ('M33_no_integration', CPA, [('else stage S1 fetch_integrate; s1_integrate S1 1; fi', 'else stage S1 fetch_integrate; fi')], '7 merge', 'S1 never integrates a diverged repository'),
 ('M34_merge_conflict_is_success', CPA, [('fail "$st" 12 "${reason:-merge_blocked}"', 'log "${reason:-merge_blocked}"')], '7 merge', 'a merge that stopped on a conflict is read as success'),
 ('M35_no_s1a_backup', CPA, [('if [ -n "$CBI" ]; then stage S1a fetch_objects; s1a_backup', 'if [ -n "$CBI" ]; then stage S1a fetch_objects')], '7 merge', 'the S1a backup is skipped'),
 ('M36_bundle_not_verified', CPA, [(' && git -C "$TARGET" bundle verify "$bk/local.bundle" >>"$LOG" 2>&1 \\', ' \\')], '7 merge', 'the backup bundle is not verified'),
 ('M37_held_push_not_mapped', CPA, [('    14) HELD=1 ;;', '    14) ;;'), ('  ! grep -qE \'^HELD\' "$CPA_RUN/push.out" || HELD=1', '  :')], '6 held', 'a held remainder of S6 is not mapped to exit 14'),
 ('M38_pins_unmatched_ignored', CPA, [('if [ -s "$CPA_RUN/pins.unmatched" ]; then fail S7 15', 'if false; then fail S7 15')], '8 verifier', 'pointer drift that matches no pending move is not refused'),
 ('M39_path_in_submodule_removed', CPA, [('case "$p" in "$gl"/*) fail S2 20 path_in_submodule', 'case "$p" in "$gl"/*) log path_in_submodule')], '2 usage', 'path_in_submodule is not refused at S2', 'equivalent: commit_recursive.sh refuses the same path with 20 path_in_submodule at S5 (second layer), so the matrix result is unchanged'),
 ('M40_resolution_dir_check_removed', CPA, [('case "$rrd" in "$(cd "$ROOT" && pwd -P)/.audit/merge-resolution/"?*) ;; *) fail S0 20 resolution_dir_invalid "$rrd" ;; esac', ':')], '7 merge', 'the --resolve-merge directory is not checked by CPA', 'equivalent: integrate_merge.sh --resolution refuses the same directory with 20 resolution_dir_invalid (second layer)'),
 ('M41_awaits_review_ignored', CPA, [('AWAIT="$2"; shift 2 ;;\n    --repo)', 'AWAIT=""; shift 2 ;;\n    --repo)')], '6 held', '--awaits-review is parsed and dropped: a path without its own verdict is not held'),
 ('M42_long_gate_missing_ignored', CPA, [('1) fail S4 10 long_gate_verdict_missing', '1) log S4_ignored')], '4 deferral', 'a missing long-gate verdict does not stop the run'),
 ('M43_live_holder_not_refused', CPA, [('[ -z "$holder" ] || fail S0 20 lock_held "a live run is mid-merge:', '[ -z "$holder" ] || log "a live run is mid-merge:')], '7 merge', 'a live holder paused mid-merge is treated as an interrupted run'),
 ('M44_ff_status_outside_set_is_success', CPA, [('*) fail "$st" 20 internal_error "integrate_ff_only.sh exit $rc" ;;', '*) return 0 ;;')], '13 helpers', 'an integrate_ff_only.sh exit outside its documented set is read as success'),
 ('M45_verifier_blind_ignored', CPA, [('20) fail S7 20 verifier_blind "verifier exit 20" ;;', '20) ;;')], '13 helpers', 'a blind verifier (exit 20) with a readable report is read as clean'),
 ('M46_s1a_unrecorded_guard_removed', CPA, [('fail S1a 20 unrecorded_local_commit', 'log S1a_ignored unrecorded_local_commit')], '7 merge', 'the S1a guard against a commit that no run recorded is removed'),
 ('M47_pending_check_is_zero', CPA, [('14) PENDING_CHECKS=1 ;;', '14) ;;')], '4 deferral', 'a check_pending_release row does not make the run exit 14'),
 ('M48_host_empty_trust_file_accepted', HOST, [('[ -s "$TRUST" ] || refuse project_not_trusted trust_file_absent', '[ -r "$TRUST" ] || refuse project_not_trusted trust_file_absent')], '10 host', 'an empty trust file is read as present (jq 1.6 exits 0 on empty input)'),
]
